[project]
name = "kmeans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "image>=1.5.33",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "requests>=2.32.3",
]
